export default {
    "LB":{
        "title":"Lower Berth",
        "columns":[
            {
                "id":"1",
                "seats":[
                    {  "id":"LB1",
                        "type":"sleeper",
                        "isBlank":true
                    },
                     {
                        "id":"LB4",
                        "type":"sleeper",
                        "isBlank":false
                    },
                     {
                        "id":"LB7",
                        "type":"sleeper",
                        "isBlank":false
                    },
                     {
                        "id":"LB10",
                        "type":"sleeper",
                        "isBlank":false
                    },
                     {
                        "id":"LB13",
                        "type":"sleeper",
                        "isBlank":false
                    }
                ]
            },
            {
                "id":"2",
                "seats":[
                         {
                        "id":"LB34",
                        "type":"seater",
                        "isBlank":true
                    },
                ]
            },
            {
                "id":"3",
                "seats":[
                    {
                        "id":"LB2",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB5",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB8",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB11",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB14",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB17",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB20",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB23",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB26",
                        "type":"sleeper",
                        "isBlank":false
                    }
                ]
            },
            {
                "id":"4",
                "seats":[
                    {   
                        "id":"LB3",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB6",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB9",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB12",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB15",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB18",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB21",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB24",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"LB27",
                        "type":"sleeper",
                        "isBlank":false
                    },
                     
                     
                ]
            }
        ]
    },
     "UB":{
        "title":"Upper Berth",
        "columns":[
            {
                "id":"1",
                "seats":[
                    {  "id":"UB1",
                        "type":"sleeper",
                        "isBlank":true
                    },
                     {
                        "id":"UB4",
                        "type":"sleeper",
                        "isBlank":false
                    },
                     {
                        "id":"UB7",
                        "type":"sleeper",
                        "isBlank":false
                    },
                     {
                        "id":"UB10",
                        "type":"sleeper",
                        "isBlank":false
                    },
                     {
                        "id":"UB13",
                        "type":"sleeper",
                        "isBlank":false
                    }
                ]
            },
            {
                "id":"2",
                "seats":[
                         {
                        "id":"UB34",
                        "type":"seater",
                        "isBlank":true
                    },
                ]
            },
            {
                "id":"3",
                "seats":[
                    {
                        "id":"UB2",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB5",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB8",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB11",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB14",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB17",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB20",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB23",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB26",
                        "type":"sleeper",
                        "isBlank":false
                    }
                ]
            },
            {
                "id":"4",
                "seats":[
                    {   
                        "id":"UB3",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB6",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB9",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB12",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB15",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB18",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB21",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB24",
                        "type":"seater",
                        "isBlank":false
                    },
                     {
                        "id":"UB27",
                        "type":"sleeper",
                        "isBlank":false
                    },
                     
                     
                ]
            }
        ]
    },
}